Repository wfxr/forgit, pull requests merged in 2019-11, with the labels that each got.

#46 Fixed readme and added fzf check to zsh to be the same as fish version
  README.md
  forgit.plugin.fish
  forgit.plugin.zsh
Labels: enhancement

#48 Adding a PR template
  .github/pull_request_template.md
Labels: improvement

#58 Fix path related bugs.
  forgit.plugin.zsh
Labels: bug, enhancement
